clc; clearvars; close all;
num_images=32;
rem = [8,12,14,16,24,26,30,6,32];
JPG=[3,4,5,10,25];
index=[1,28,4,10,18,15,11,19,22,23,13,27,05,07,29,17,09,31,02,25,20,21,3,8,12,14,16,24,26,30,6,32];
%index=randperm(num_images,num_images);
headings = ["Lunch with friends at Planta Queens in downtown Toronto after the wedding ceremony at Toronto City Hall!", ...
    "Our amateur dance sequence after the wedding ceremony in Toronto City Hall!", ...
    "Sanjana walking down the Aisle with a gorgeous flower bouquet at Toronto City Hall during the wedding ceremony!", ...
    "", ...
    "First date", ...
    "First date", ...
    "First date", ...
    "First date", ...
    "First date", ...
    "First date", ...
    "First date", ...
    "First date", ...
    "First date", ...
    "First date", ...
    "First date", ...
    "First date", ...
    "First date", ...
    "First date", ...
    "First date", ...
    "First date", ...
    "First date", ...
    "First date", ...
    "First date", ...
    "First date", ...
    "First date", ...
    "First date", ...
    "First date", ...
    "First date", ...
    "First date", ...
    "First date", ...
    "First date", ...
    "First date" ];
paragraph = ["29th February 2024", ...
    "29th February 2024", ...
    "29th February 2024", ...
    "29th February 2024", ...
    "29th February 2024", ...
    "29th February 2024", ...
    "Canoe date", ...
    "Canoe date", ...
    "Canoe date", ...
    "Canoe date", ...
    "Canoe date", ...
    "Canoe date", ...
    "Canoe date", ...
    "Canoe date", ...
    "Canoe date", ...
    "Canoe date", ...
    "Canoe date", ...
    "Canoe date", ...
    "Canoe date", ...
    "Canoe date", ...
    "Canoe date", ...
    "Canoe date", ...
    "Canoe date", ...
    "Canoe date", ...
    "Canoe date", ...
    "Canoe date", ...
    "Canoe date", ...
    "Canoe date", ...
    "Canoe date", ...
    "Canoe date", ...
    "Canoe date", ...
    "Canoe date" ];
hstr="href";
f=fopen("ourstorycode.dat","w");
for ii=1:num_images
    i=index(ii);
    if(any(i==rem))
        fprintf("Skipping image number %d\n", i);
    else
        fprintf(f,"\n");
        fprintf(f,"\t\t\t<div class=""col-lg-4 col-md-6 portfolio-item filter-remodeling"">\n");
        fprintf(f,"\t\t\t  <div class=""portfolio-content h-100"">\n");
        if(any(i==JPG))
            fprintf(f,sprintf("\t\t\t\t<img src=""assets/img/ourstory_%02d.JPG"" class=""img-fluid"" alt="""">\n", i));
        else
            fprintf(f,sprintf("\t\t\t\t<img src=""assets/img/ourstory_%02d.jpg"" class=""img-fluid"" alt="""">\n", i));
        end    
        fprintf(f,"\t\t\t\t<div class=""portfolio-info"">\n");
        fprintf(f,sprintf("\t\t\t\t  <h4>%s</h4>\n", headings(i)));
        fprintf(f,sprintf("\t\t\t\t  <p>%s</p>\n", paragraph(i)));
        fprintf(f,sprintf("\t\t\t\t  <a %s=""assets/img/ourstory_%02d.jpg"" title=""%s | %s"" data-gallery=""portfolio-gallery-remodeling"" class=""glightbox preview-link""><i class=""bi bi-zoom-in""></i></a>\n", hstr, i, paragraph(i), headings(i)));
        fprintf(f,"\t\t\t\t</div>\n");
        fprintf(f,"\t\t\t  </div>\n");
        fprintf(f,"\t\t\t</div>\n");
    end
end
fclose(f);
