clc; clearvars; close all;
num_images=32;
rem = [8,12,14,16,24,26,30,6,32];
JPG=[3,4,5,10,25];
index=[1,28,4,10,18,15,11,19,22,23,13,27,05,07,29,17,09,31,02,25,20,21,3,8,12,14,16,24,26,30,6,32];
%index=randperm(num_images,num_images);
headings = ["After saying ""I do"" at Toronto City Hall, we treated ourselves and our closest friends to a delicious vegan lunch at Planta Queen's in downtown Toronto. It was the perfect way to celebrate our love and kick off our new life together surrounded by amazing food and even better company.", ...
    "We may not be professional dancers, but we sure had fun busting out our amateur moves after our wedding ceremony at Toronto City Hall! This impromptu dance session was the perfect way to celebrate our love and let loose with pure joy.", ...
    "The elegant simplicity of Toronto City Hall provided the perfect backdrop for Sanjana's entrance, her gorgeous bouquet adding a touch of vibrant color.", ...
    "After the ceremony at Toronto City Hall, we couldn't resist indulging in a few cheesy, must-have wedding photos with our amazing friends.", ...
    "Sanjana, beaming with joy after our wedding ceremony at Toronto City Hall." ...
    "First date", ...
    "Utsav keeping Sanjana warm on their way to Jasper Parkway.", ...
    "First date", ...
    "Sanjana shivered but summoned the courage to take a picture with the stunning Alabaster Glacier.", ...
    "Finally, Utsav relented and let her take a picture of him.", ...
    "Utsav's family visits Sanjana's home and most of them meet her for the first time. They are super happy with Utsav’s choice.", ...
    "First date", ...
    "The day our families met each other and gave us a perfect green light.", ...
    "First date", ...
    "1 Not sure: Our engagement day at ", ...
    "When Sanjana officially visited Utsav's home, she was warmly welcomed by all the family members.", ...
    "2 Not sure: Filled with Gratitude for this day, Our engagement day, seeing our families enjoying together.", ...
    "Utsav and Sanjana savoring the joyful moments amid the family rituals.", ...
    "Our first trip ever together to Muskoka in the beautiful summer of 2022." ...
    "Our first camping trip together, with whales by the shore of the St. Lawrence River in Tadoussac.", ...
    "A short hike in Niagara during the summer of 2024.", ...
    "Taking a moment to pose under the beautiful gazebo during our trip to the lovely Unionville with friends.", ...
    "3 Not sure: Another great hike in nature in.", ...
    "First date", ...
    "Having some fun at the winery on our way to our first trip to Muskoka, Sanjana hadn't even considered that this trip would change her life.", ...
    "First date", ...
    "A photo from Sanjana's first-ever visit to the US and Chicago. It was also the first picture we shared with each other's parents, and we both think we looked decent in it. It did take a couple of shots to get this one right.", ...
    "Our fancy first date with the sunset on one side and the CN Tower on the other.", ...
    "We exchanged promise rings on Niagara Lake, embraced by nature's silent witness.", ...
    "First date", ...
    "Our first Halloween together with friends in Toronto. Utsav was convinced he could scare anyone, even without makeup.", ...
    "A lovely evening aboard the Kajama Sail boat, cruising along the Lakeshore in Toronto."];
paragraph = ["29th February 2024", ...
    "29th February 2024", ...
    "29th February 2024", ...
    "29th February 2024", ...
    "29th February 2024", ...
    "29th February 2024", ...
    "31st December 2022", ...
    "31st December 2022", ...
    "2nd January 2023", ...
    "2nd January 2023", ...
    "26th May 2023", ...
    "23rd May 2023", ...
    "26th March 2023", ...
    "23rd May 2023", ...
    "23rd May 2023", ...
    "28th May 2023", ...
    "23rd May 2023", ...
    "28th May 2023", ...
    "2nd July 2022", ...
    "20th August 2022", ...
    "4th May 2024", ...
    "17th February 2024", ...
    "27th December 2023", ...
    "1st October 2022", ...
    "1st July 2022", ...
    "1st October 2022", ...
    "26th December 2022", ...
    "24th June 2022", ...
    "13th August 2022", ...
    "1st November 2022", ...
    "1st November 2022", ...
    "28th June 2022" ];
hstr="href";
f=fopen("ourstorycode.dat","w");
for ii=1:num_images
    i=index(ii);
    if(any(i==rem))
        fprintf("Skipping image number %d\n", i);
    else
        fprintf(f,"\n");
        fprintf(f,"\t\t\t<div class=""col-lg-4 col-md-6 portfolio-item filter-remodeling"">\n");
        fprintf(f,"\t\t\t  <div class=""portfolio-content h-100"">\n");
        if(any(i==JPG))
            fprintf(f,sprintf("\t\t\t\t<img src=""assets/img/ourstory_%02d.JPG"" class=""img-fluid"" alt="""">\n", i));
        else
            fprintf(f,sprintf("\t\t\t\t<img src=""assets/img/ourstory_%02d.jpg"" class=""img-fluid"" alt="""">\n", i));
        end    
        fprintf(f,"\t\t\t\t<div class=""portfolio-info"">\n");
        fprintf(f,sprintf("\t\t\t\t  <h4>%s</h4>\n", headings(i)));
        fprintf(f,sprintf("\t\t\t\t  <p>%s</p>\n", paragraph(i)));
        if(any(i==JPG))
            fprintf(f,sprintf("\t\t\t\t  <a %s=""assets/img/ourstory_%02d.JPG"" title=""%s | %s"" data-gallery=""portfolio-gallery-remodeling"" class=""glightbox preview-link""><i class=""bi bi-zoom-in""></i></a>\n", hstr, i, paragraph(i), headings(i)));
        else
            fprintf(f,sprintf("\t\t\t\t  <a %s=""assets/img/ourstory_%02d.jpg"" title=""%s | %s"" data-gallery=""portfolio-gallery-remodeling"" class=""glightbox preview-link""><i class=""bi bi-zoom-in""></i></a>\n", hstr, i, paragraph(i), headings(i)));
        end
        fprintf(f,"\t\t\t\t</div>\n");
        fprintf(f,"\t\t\t  </div>\n");
        fprintf(f,"\t\t\t</div>\n");
    end
end
fclose(f);
