clc; clearvars; close all;
num_images=32;
rem = [8,12,14,16,24,26,30,6,32];
JPG=[3,4,5,10,25];
index=[1,28,4,10,18,15,11,19,22,23,13,27,05,07,29,17,09,31,02,25,20,21,3,8,12,14,16,24,26,30,6,32];
%index=randperm(num_images,num_images);
headings = ["After saying ""I do"" at Toronto City Hall, we treated ourselves and our closest friends to a delicious vegan lunch at Planta Queen's in downtown Toronto. It was the perfect way to celebrate our love and kick off our new life together surrounded by amazing food and even better company.", ...
    "We may not be professional dancers, but we sure had fun busting out our amateur moves after our wedding ceremony at Toronto City Hall! This impromptu dance session was the perfect way to celebrate our love and let loose with pure joy.", ...
    "The elegant simplicity of Toronto City Hall provided the perfect backdrop for Sanjana's entrance, her gorgeous bouquet adding a touch of vibrant color.", ...
    "After the ceremony at Toronto City Hall, we couldn't resist indulging in a few cheesy, must-have wedding photos with our amazing friends.", ...
    "Sanjana, beaming with joy after our wedding ceremony at Toronto City Hall." ...
    "First date", ...
    "Utsav kept Sanjana warm as they made their way through the breathtaking icefield parkway in Alberta.", ...
    "First date", ...
    "Sanjana shivered but summoned the courage to take a picture with the stunning Athabasca Glacier.", ...
    "Finally, Utsav relented and let Sanjana take a picture of him.", ...
    "Utsav's family joyfully visited Sanjana's home, and many of them met her for the first time. They were absolutely delighted with Utsav's choice.", ...
    "First date", ...
    "The joyful day our families came together and gave us their heartfelt blessing to begin our journey together.", ...
    "First date", ...
    "Celebrating a triple dose of love and laughter: our engagement day coincided with our parents' anniversary, so we marked the occasion with a joyous dinner outside Ahmedabad alongside both of our families. We couldn't resist capturing the moment with a slightly cheesy but heartfelt photo, a memory we'll cherish forever.", ...
    "When Sanjana officially visited Utsav's home, she was showered with warmth and affection by every member of his family.", ...
    "The day our lives changed forever: we got engaged, our families met, and we dressed up to celebrate the beginning of our happily ever after.", ...
    "Utsav and Sanjana savoring the joyful moments amidst the cherished family rituals.", ...
    "Our very first adventure together, a memorable trip to the picturesque Muskoka region in the summer of 2022." ...
    "Our first camping adventure together, where we were mesmerized by the sight of whales breaching near the shore of the majestic St. Lawrence River in Tadoussac.", ...
    "A refreshing hike amidst the stunning natural beauty of Niagara during the summer of 2024, where we had the unexpected thrill of encountering a snake and the delightful surprise of spotting a beaver.", ...
    "Pausing for a picture beneath the charming gazebo, surrounded by the picturesque scenery of Unionville, during a delightful outing with friends.", ...
    "During Sanjana's visit to Purdue for Christmas 2023, we embarked on a peaceful hike near Indianapolis, indulging in our shared passion for exploring nature's tranquility.", ...
    "First date", ...
    "Enjoying some lighthearted moments at the winery during our first trip to Muskoka, little did Sanjana know that this journey would change her life forever.", ...
    "First date", ...
    "A cherished photo taken in downtown Toronto. This marked the first picture we shared with each other's parents, and we both agree we looked quite presentable, even if it took a few tries to capture the perfect shot.", ...
    "Our unforgettable first date at Canoe, located on the 85th floor, where we were treated to a breathtaking view of the sunset on one side and the iconic CN Tower on the other.", ...
    "On the tranquil shores of Niagara Lake, we exchanged promise rings, surrounded by the quiet beauty of nature, a silent witness to our commitment.", ...
    "First date", ...
    "Our first Halloween together, celebrating with friends in Toronto. Utsav, ever confident, believed he could frighten anyone, even without the aid of makeup.", ...
    "A romantic evening aboard the majestic Kajama sailboat, gently cruising along the picturesque Toronto lakeshore."];
paragraph = ["29th February 2024", ...
    "29th February 2024", ...
    "29th February 2024", ...
    "29th February 2024", ...
    "29th February 2024", ...
    "29th February 2024", ...
    "31st December 2022", ...
    "31st December 2022", ...
    "2nd January 2023", ...
    "2nd January 2023", ...
    "26th May 2023", ...
    "23rd May 2023", ...
    "26th March 2023", ...
    "23rd May 2023", ...
    "23rd May 2023", ...
    "28th May 2023", ...
    "23rd May 2023", ...
    "28th May 2023", ...
    "2nd July 2022", ...
    "20th August 2022", ...
    "4th May 2024", ...
    "17th February 2024", ...
    "27th December 2023", ...
    "1st October 2022", ...
    "1st July 2022", ...
    "1st October 2022", ...
    "26th December 2022", ...
    "24th June 2022", ...
    "13th August 2022", ...
    "1st November 2022", ...
    "1st November 2022", ...
    "28th June 2022" ];
hstr="href";
f=fopen("ourstorycode.dat","w");
for ii=1:num_images
    i=index(ii);
    if(any(i==rem))
        fprintf("Skipping image number %d\n", i);
    else
        fprintf(f,"\n");
        fprintf(f,"\t\t\t<div class=""col-lg-4 col-md-6 portfolio-item filter-remodeling"">\n");
        fprintf(f,"\t\t\t  <div class=""portfolio-content h-100"">\n");
        if(any(i==JPG))
            fprintf(f,sprintf("\t\t\t\t<img src=""assets/img/ourstory_%02d.JPG"" class=""img-fluid"" alt="""">\n", i));
        else
            fprintf(f,sprintf("\t\t\t\t<img src=""assets/img/ourstory_%02d.jpg"" class=""img-fluid"" alt="""">\n", i));
        end    
        fprintf(f,"\t\t\t\t<div class=""portfolio-info"">\n");
        fprintf(f,sprintf("\t\t\t\t  <h4>%s</h4>\n", headings(i)));
        fprintf(f,sprintf("\t\t\t\t  <p>%s</p>\n", paragraph(i)));
        if(any(i==JPG))
            fprintf(f,sprintf("\t\t\t\t  <a %s=""assets/img/ourstory_%02d.JPG"" title=""%s | %s"" data-gallery=""portfolio-gallery-remodeling"" class=""glightbox preview-link""><i class=""bi bi-zoom-in""></i></a>\n", hstr, i, paragraph(i), headings(i)));
        else
            fprintf(f,sprintf("\t\t\t\t  <a %s=""assets/img/ourstory_%02d.jpg"" title=""%s | %s"" data-gallery=""portfolio-gallery-remodeling"" class=""glightbox preview-link""><i class=""bi bi-zoom-in""></i></a>\n", hstr, i, paragraph(i), headings(i)));
        end
        fprintf(f,"\t\t\t\t</div>\n");
        fprintf(f,"\t\t\t  </div>\n");
        fprintf(f,"\t\t\t</div>\n");
    end
end
fclose(f);
